# Generated by Django 4.0.2 on 2022-04-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law_enforcement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='case',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='case',
            name='photo_3',
        ),
    ]
