# Generated by Django 4.0.2 on 2022-04-10 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('law_enforcement', '0003_lineup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Officer',
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='Witness',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_officer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_witness',
        ),
        migrations.AlterField(
            model_name='lineup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
