# Generated by Django 4.0.2 on 2022-04-13 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('law_enforcement', '0004_rename_employee_officer_rename_customer_witness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='finalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.IntegerField()),
                ('ide_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='law_enforcement.photo')),
            ],
        ),
    ]
