# Generated by Django 4.0.2 on 2022-04-13 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('law_enforcement', '0005_finalphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalphoto',
            name='ide_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='law_enforcement.lineup'),
        ),
    ]
