# Generated by Django 4.0.2 on 2022-04-13 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_enforcement', '0006_alter_finalphoto_ide_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 13, 11, 55, 11, 911077)),
        ),
    ]
