# Generated by Django 4.0.2 on 2022-04-23 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_enforcement', '0009_user_logout_time_alter_user_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 23, 16, 55, 37, 495154)),
        ),
        migrations.AlterField(
            model_name='user',
            name='logout_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 23, 16, 55, 37, 496154)),
        ),
    ]
